version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/
    ports:
      - ${NGINX_HOST_HTTP_PORT}:8080
    networks:
      - app-network  # Додайте контейнер до мережі

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network  # Додайте контейнер до тієї ж мережі

networks:
  app-network:
    driver: bridge  # Забезпечте, що використовуєте "bridge" мережу

volumes:
  mysql-data:
